### ISSUE TITLE
libressl 的支持

### ISSUE THREAD

**Issue by oahong** [mytbk/fqterm#12]
Hi， 编译fqterm时有如下报错，能添加libressl的支持不？
谢谢
make[2]: Leaving directory '/var/tmp/paludis/build/x11-misc-fqterm-0.9.8.4/work/fqterm-0.9.8.4'
make[1]: Leaving directory '/var/tmp/paludis/build/x11-misc-fqterm-0.9.8.4/work/fqterm-0.9.8.4'
src/protocol/libfqterm_protocol.a(ssh_diffie-hellman.c.o): In function `ssh_dh_group1_sha1':
ssh_diffie-hellman.c:(.text+0x27): undefined reference to `EVP_MD_CTX_new'
src/protocol/libfqterm_protocol.a(ssh_diffie-hellman.c.o): In function `ssh_dh_group14_sha1':
ssh_diffie-hellman.c:(.text+0x97): undefined reference to `EVP_MD_CTX_new'
src/protocol/libfqterm_protocol.a(ssh_diffie-hellman.c.o): In function `ssh_dh_free':
ssh_diffie-hellman.c:(.text+0xfc): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fqterm.bin.dir/build.make:123: fqterm.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/fqterm.bin.dir/all] Error 2
make: *** [Makefile:153: all] Error 2

**Comment by mytbk** [comment]
试试这个patch.

```
diff --git a/src/protocol/internal/ssh_diffie-hellman.h b/src/protocol/internal/ssh_diffie-hellman.h
index f132493..0716d48 100644
--- a/src/protocol/internal/ssh_diffie-hellman.h
+++ b/src/protocol/internal/ssh_diffie-hellman.h
@@ -5,7 +5,8 @@
 #include <openssl/sha.h>
 #include <openssl/evp.h>
 
-#if OPENSSL_VERSION_NUMBER >= 0x10100000L
+#if OPENSSL_VERSION_NUMBER >= 0x10100000L && \
+       !defined(LIBRESSL_VERSION_NUMBER)
 #define ssh_md_ctx_new EVP_MD_CTX_new
 #define ssh_md_ctx_free EVP_MD_CTX_free
 #else
```

**Comment by mytbk** [comment]
似乎还是不太对，你能不能说一下你用的 libressl 是什么版本？

**Comment by oahong** [comment]
patch 实测有效，谢谢。

**Comment by mytbk** [comment]
cherry-picked to master
