### ISSUE TITLE
Missing include QButtonGroup in header files

### ISSUE THREAD

**Issue by xuzhao9** [mytbk/fqterm#15]
Need to add 
```C
#include<QButtonGroup>
```
in addrdialog.h, keydialog.h, prefdialog.h, schemadialog.h, soundconf.h to build against Qt 5.11.

**Comment by mytbk** [comment]
They are already in the latest git code. Have you checked it out?

**Comment by xuzhao9** [comment]
I was using 0.9.9 release. The git version looks like to be fixed so I just close this issue.
