### ISSUE TITLE
Function does not return any value, causing compiling warning

### ISSUE THREAD

**Issue by xuzhao9** [mytbk/fqterm#19]
buffer_append_byte():
https://github.com/mytbk/fqterm/blob/master/src/protocol/internal/buffer.c#L76
buffer_append_be16():
https://github.com/mytbk/fqterm/blob/master/src/protocol/internal/buffer.c#L86
buffer_append_be32():
https://github.com/mytbk/fqterm/blob/master/src/protocol/internal/buffer.c#L97

They should return some value on all branches, not just else branch.

Similar thing in:
https://github.com/mytbk/fqterm/blob/master/src/protocol/internal/fqterm_ssh_packet.cpp#L153
and
https://github.com/mytbk/fqterm/blob/master/src/protocol/internal/fqterm_ssh_packet.cpp#L161

**Comment by mytbk** [comment]
fixed
