### ISSUE TITLE
Differences vs QTerm?

### ISSUE THREAD

**Issue by hyiltiz** [mytbk/fqterm#21]
The README.md mentions fqterm was forked from an old QTerm [1]. Both fqterm and QTerm has evolved to Qt5 so far. QTerm seems to support many more encodings than fqterm, but QTerm failed to log into a few bbs (e.g. test with bbs.pku.edu.cn) with any settings at all while fqterm could connect without issues with default settings. What is fundamentally different?

[1] https://github.com/qterm/qterm

**Comment by mytbk** [comment]
Looks like QTerm has something wrong when doing an ssh handshake with bdwm.net.
The SSH features implemented in QTerm and FQTerm are different. It's not recommended to use the native SSH implementation for security reasons, you can use your local openssh instead if possible. In FQTerm you can choose "Local" when selecting a protocol.
bdwm.net has now banned telnet outside school.[1]

[1] https://bbs.pku.edu.cn/v2/post-read.php?bid=16&threadid=17524991

**Comment by hyiltiz** [comment]
Thanks! 
- PsySunrise
