### ISSUE TITLE
Debian 打包发现的拼写错误补丁

### ISSUE THREAD

**Issue by atzlinux** [mytbk/fqterm#22]
fix-spelling-error-fqterm_decode.cpp.patch 
Description: fix type error
 lintian check I: fqterm: spelling-error-in-binary usr/bin/fqterm.bin

---
Origin: xiao sheng wen <atzlinux@sina.com>
Last-Update: 2020-05-17

```
--- fqterm-0.9.9.orig/src/terminal/internal/fqterm_decode.cpp
+++ fqterm-0.9.9/src/terminal/internal/fqterm_decode.cpp
@@ -324,7 +324,7 @@ const char *FQTermDecode::getStateName(c
   } else if (state == VT100StateMachine::title_state_) {
     return "VT100StateMachine::title_state_";
   } else {
-    return "Unknow";
+    return "Unknown";
   }
 }

```

**Comment by hosiet** [comment]
https://github.com/mytbk/fqterm/pull/16

**Comment by atzlinux** [comment]
这个是重复报告了。

建议上游发布一个新版本吧，把 0.9.9 版本以来的补丁集成发布。

**Comment by mytbk** [comment]
我刚刚做了个 0.9.10 的 tag.
