### ISSUE TITLE
三个小问题

### ISSUE THREAD

**Issue by jszhao** [mytbk/fqterm#28]
1）大概两个月前（不那么确定），windows 下的 fqterm 0.9.9 不能预览水木社区上的图片了，会一直显示 `0% 获取文件头......`
2）关于中三个链接，第二个的 github 显示 404，第三个实际是指向第一个链接。
3）可否放出新的 windows 版本啊。自已不知道怎么编译……

多谢！！

**Comment by pangwa** [comment]
0.9.10版本倒是可以工作的。。。

**Comment by jszhao** [comment]
没有 windows 下可用的二进制版本啊，不会从源码编译……

**Comment by pangwa** [comment]
试试这个， 是动态链接版本， 可以正常下载和预览图片。
[fqterm.zip](https://github.com/mytbk/fqterm/files/8775345/fqterm.zip)

**Comment by jszhao** [comment]
多谢！可以了。

**Comment by pangwa** [comment]
上个版本有一个鼠标滚动两次的bug， 用这个文件替换原目录中的同名文件就可以修复。

[fqterm.zip](https://github.com/mytbk/fqterm/files/8783447/fqterm.zip)

**Comment by jszhao** [comment]
多谢！

**Comment by jszhao** [comment]
现在这个二进制版本如果能放在 [Releases](https://github.com/mytbk/fqterm/releases)页面就方便了。现在，这个issues可以关掉了。
