### ISSUE TITLE
关于页面上的链接指向 code.google 而非 github

### ISSUE THREAD

**Issue by jszhao** [mytbk/fqterm#34]
我用的版本如下图所示。同时，下图上的那个链接实际上是指向 [code.google](https://code.google.com/p/fqterm) 
![fqterm](https://user-images.githubusercontent.com/12680518/170802981-c91b3f57-5c92-4e60-9cbc-6b4748a76c85.png)

**Comment by mytbk** [comment]
已经用 commit 1d9be2e96a8144b8eb3cf688ec46c5dc4b010860 修复。
