### ISSUE TITLE
ssh connection not work

### ISSUE THREAD

**Issue by pangwa** [mytbk/fqterm#35]
connect to mysmth.net using the ssh connection type, it reports "decrypt error!
![image](https://github.com/mytbk/fqterm/assets/927678/08145efb-6dc1-496f-b146-47a41b2ec014)

**Comment by atzlinux** [comment]
I meet the same bug, please fix it.

**Comment by mytbk** [comment]
I've pushed a change in commit 634b961, this may solve the problem.
I don't recommend using the native SSH connection if you have OpenSSH installed. https://github.com/mytbk/fqterm/blob/master/doc/SSH.md

**Comment by pangwa** [comment]
The fix works on my side. Thanks! 

> I've pushed a change in commit [634b961](https://github.com/mytbk/fqterm/commit/634b9612179c289c9f8c7ed18b25a0439a598131), this may solve the problem. I don't recommend using the native SSH connection if you have OpenSSH installed. https://github.com/mytbk/fqterm/blob/master/doc/SSH.md
